export const DOCUMENT_ADMIN_LOG_ACTIONS = {
  PROPOSAL_SENT: 'DOCUMENT_PROPOSAL_SENT',
  DOSSIER_SENT: 'DOCUMENT_DOSSIER_SENT',
  DOSSIER_COMPOSITE_PDF_GENERATED: 'DOCUMENT_DOSSIER_COMPOSITE_PDF_GENERATED',
  CONTRACT_GENERATED: 'DOCUMENT_CONTRACT_GENERATED',
  CONTRACT_SENT: 'DOCUMENT_CONTRACT_SENT',
  CONTRACT_SIGNED: 'DOCUMENT_CONTRACT_SIGNED',
  CONTRACT_CANCELLED: 'DOCUMENT_CONTRACT_CANCELLED',
  CONTRACT_SIGNED_PDF_GENERATED: 'DOCUMENT_CONTRACT_SIGNED_PDF_GENERATED',
} as const;
