export type MasterAtlasNextMove = {
  label: string;
  why: string;
  impact: 'ALT' | 'MITJA' | 'BAIX';
  effort: 'BAIX' | 'MITJA' | 'ALT';
  status: 'FET' | 'EN_CURS' | 'PENDENT';
};

export type MasterAtlasZenitImprovement = {
  label: string;
  area: 'VENDA' | 'OPERACIO' | 'MARGE' | 'MARCA' | 'SISTEMA';
  current: string;
  zenit: string;
  why: string;
  impact: 'ALT' | 'MITJA' | 'BAIX';
  effort: 'BAIX' | 'MITJA' | 'ALT';
  status: 'FET' | 'EN_CURS' | 'PENDENT';
};

export type MasterAtlasActualToZenit = {
  current: string;
  zenit: string;
  superintendentRead: string;
  improvements: MasterAtlasZenitImprovement[];
};

export type MasterAtlasModuleDefinition = {
  id: string;
  title: string;
  subtitle: string;
  mission: string;
  ownerQuestion: string;
  routes: string[];
  visualGroups: string[];
  electricPatterns: string[];
  sourceOfTruth: string[];
  docs: string[];
  operations: string[];
  risks: string[];
  safeTouch: string[];
  validations: string[];
  nextMoves: MasterAtlasNextMove[];
};

export const MASTER_ATLAS_PRINCIPLES = [
  'Radiografia real abans de tocar: atles electric, atles visual i protocol viuen per davant de la intuicio.',
  'Una sola font de veritat per cada decisio: servei o constant canonica, mai calcul local en JSX.',
  'Lead configura; booking governa despres del si; dossier presenta sense ensenyar la cuina interna.',
  'Marge, cash i capacitat decideixen abans que el propietari es comprometi.',
  'Qualsevol sortida cap al client necessita plantilla editable, lock idempotent i fallback manual.',
  'Cada modul ha de dir que fa, on viu, que no tocar i com validar-se.',
] as const;

export const MASTER_ATLAS_GATES = [
  'Protocol llegit i agent-sync actualitzat.',
  'Font canonica identificada.',
  'Ruta real o document visible afectat.',
  'Test o guard proporcional al risc.',
  'Validacio funcional amb dades reals o fixture representatiu.',
  'Validacio humana/UX escrita.',
  'Diari + protocol + counter sincronitzats.',
] as const;

export const MASTER_ATLAS_ACTUAL_TO_ZENIT: Record<string, MasterAtlasActualToZenit> = {
  comandament: {
    current: 'Avui ja concentra tasques, leads, post-event, alertes de capacitat i números principals; el control complet queda separat.',
    zenit: 'Una cabina executiva que decideix la jornada: què vendre, què protegir, què cobrar i què no acceptar.',
    superintendentRead: 'El propietari no necessita més dades; necessita ordre de batalla, prioritat i frens abans de comprometre dissabtes cars.',
    improvements: [
      {
        label: 'Brief executiu abans d obrir l admin',
        area: 'OPERACIO',
        current: 'El brief existeix dins la pantalla Avui.',
        zenit: 'Arriba sol amb les 3 decisions del dia, riscos i oportunitats de venda.',
        why: 'Redueix fricció i converteix el dashboard en agenda real.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Semàfor de dissabtes i dies premium',
        area: 'MARGE',
        current: 'La col·lisió de dia ja s avisa quan hi ha 2+ bolos.',
        zenit: 'Cada data escassa té lectura econòmica: marge esperat, equip, risc i preu mínim recomanat.',
        why: 'Un dissabte no es ven com un dimarts; és inventari premium.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'EN_CURS',
      },
      {
        label: 'Accions de 1 clic des de Cal que ho miris',
        area: 'SISTEMA',
        current: 'Les alertes expliquen què passa i envien al detall.',
        zenit: 'Cada alerta proposa el següent clic segur: confirmar, crear tasca, obrir reserva o preparar missatge.',
        why: 'La pantalla ha de treure feina, no només assenyalar-la.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
    ],
  },
  comercial: {
    current: 'Els leads tenen scoring, prioritat a Avui i welcome automàtic amb fallback manual.',
    zenit: 'Una màquina comercial que respon ràpid, segmenta valor, prepara oferta i no deixa cap oportunitat bona refredar-se.',
    superintendentRead: 'La venda de milers d euros depèn de rapidesa, percepció premium i una propera acció sempre clara.',
    improvements: [
      {
        label: 'Guió comercial per tipus de client i esdeveniment',
        area: 'VENDA',
        current: 'El sistema prioritza leads però no sempre diu quin angle de venda usar.',
        zenit: 'Cada lead obre amb argumentari, objeccions probables i paquet recomanat.',
        why: 'Millora conversió sense carregar el propietari de pensar des de zero.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Oferta recomanada amb paquet, extres i marge',
        area: 'MARGE',
        current: 'LeadServiceLine configura abans de reserva i els dossiers poden mapar línies.',
        zenit: 'El lead suggereix una proposta premium defensable amb upsells i marge visible abans d enviar.',
        why: 'La web ha de vendre valor i protegir benefici, no només prendre nota.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
      {
        label: 'Cadència multicanal amb aturada humana',
        area: 'VENDA',
        current: 'Welcome automàtic resol el primer toc.',
        zenit: 'Seqüència email/WhatsApp/tasca que s atura si el client respon o si hi ha risc de soroll.',
        why: 'Cap lead calent hauria de morir per silenci.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
    ],
  },
  documents: {
    current: 'Dossiers i PDFs ja tenen snapshot, marge previ, auto-esborrany segur i PDF compost.',
    zenit: 'Un sistema de proposta que sembla agència premium: explica valor, justifica preu i accelera el sí sense ensenyar la cuina.',
    superintendentRead: 'El dossier és el venedor quan el propietari no hi és; ha de convertir confiança en preu acceptat.',
    improvements: [
      {
        label: 'Revisió editorial del dossier complet',
        area: 'MARCA',
        current: 'La infraestructura és forta i estable.',
        zenit: 'La narrativa, jerarquia visual i prova social estan afinades per vendre imports alts.',
        why: 'Una proposta cara necessita percepció cara, clara i segura.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Comparativa de paquets i upsells dins proposta',
        area: 'VENDA',
        current: 'El client veu proposta i serveis seleccionats.',
        zenit: 'El document guia cap a una opció recomanada i mostra extres naturals sense semblar un catàleg fred.',
        why: 'Augmenta ticket mitjà sense pressionar.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Control final abans d enviar',
        area: 'MARGE',
        current: 'Hi ha marge abans d enviar.',
        zenit: 'El botó d enviament resumeix marge, risc, data premium, snapshot i copy client-facing.',
        why: 'Evita enviar propostes boniques però poc rendibles.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'EN_CURS',
      },
    ],
  },
  reserves: {
    current: 'La reserva governa després del sí; hi ha checklist, inventari, calendari, capacitat i guàrdia de dies amb 2+ bolos.',
    zenit: 'Una torre de control d esdeveniments: cap bolo confirmat sense equip, inventari, timings, caixa i risc entesos.',
    superintendentRead: 'La venda només és bona si el dia s executa impecable i no crema el següent bolo.',
    improvements: [
      {
        label: 'Gate de data ocupada en crear reserva',
        area: 'OPERACIO',
        current: 'Avui avisa quan ja existeixen col·lisions de dia.',
        zenit: 'El sistema demana confirmació abans de comprometre el segon bolo en una data ocupada.',
        why: 'Prevenir costa menys que arreglar agenda compromesa.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Checklist intel·ligent T-7/T-2',
        area: 'OPERACIO',
        current: 'El checklist existeix però encara depèn massa de revisió manual.',
        zenit: 'Recordatoris i tasques canòniques apareixen segons data, estat i risc del bolo.',
        why: 'La qualitat d execució no pot dependre de memòria oral.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Fitxa de producció premium',
        area: 'MARCA',
        current: 'La fitxa reserva concentra informació interna.',
        zenit: 'La fitxa és un runbook clar: qui, què, quan, risc, equip, cobrament i pla B.',
        why: 'Fa que cada bolo sembli produït per una empresa gran.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
    ],
  },
  economia: {
    current: 'CostEngine, transport, cash-aware outstanding i compte corrent ja existeixen com a cervells reutilitzables.',
    zenit: 'Cap decisió comercial o operativa important es pren sense marge, caixa, CAC, temps escàs i risc visibles.',
    superintendentRead: 'Mirada ESADE: no es tracta de vendre més bolos, sinó de vendre millor, cobrar abans, protegir dies premium i automatitzar frens quan el marge no acompanya.',
    improvements: [
      {
        label: 'Preu mínim recomanat per data i risc',
        area: 'MARGE',
        current: 'El marge es calcula, però encara no governa prou la decisió de preu.',
        zenit: 'El sistema recomana preu mínim segons cost, CAC, dissabte, equip i ocupació.',
        why: 'Evita regalar dates cares i força disciplina comercial.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
      {
        label: 'Cash forecast accionable',
        area: 'MARGE',
        current: 'Hi ha lectura de caixa i pendent cash-aware.',
        zenit: 'El propietari veu quins cobraments moure avui i quin impacte tenen a 7/30 dies.',
        why: 'La caixa operativa és una palanca de tranquil·litat i decisió.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Auditoria de tarifes per marge real',
        area: 'VENDA',
        current: 'Els preus existeixen en catàlegs i serveis.',
        zenit: 'Els packs i extres indiquen marge real i recomanació de pujada o paquetització.',
        why: 'Un negoci premium ha de pujar preus on el sistema demostra valor i cost.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
    ],
  },
  partners: {
    current: 'Partners i CLIENT_PARTNER ja tenen fitxa, productes, compte corrent i distinció li dec/em deu.',
    zenit: 'Una xarxa de col·laboradors que amplia oferta sense desordenar marge, responsabilitat ni experiència client.',
    superintendentRead: 'Els partners han de fer vendre més i operar millor; si embruten comptes o qualitat, resten.',
    improvements: [
      {
        label: 'Scorecard de partner',
        area: 'OPERACIO',
        current: 'La fitxa mostra relació i compte corrent.',
        zenit: 'Cada partner té fiabilitat, marge, incidències, volum i propera liquidació.',
        why: 'Permet decidir amb qui créixer i amb qui anar amb cura.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Catàleg partner amb cost i markup garantits',
        area: 'MARGE',
        current: 'Els productes de partner poden entrar a dossier i cost.',
        zenit: 'Cap producte de partner es ven sense cost, preu, marge i responsabilitat clars.',
        why: 'Evita marge fictici i problemes de servei.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Liquidació mensual guiada',
        area: 'SISTEMA',
        current: 'El compte corrent explica saldo.',
        zenit: 'El sistema proposa què pagar, què cobrar i què deixar pendent amb traça.',
        why: 'Tanca el mes sense fulls paral·lels.',
        impact: 'MITJA',
        effort: 'MITJA',
        status: 'PENDENT',
      },
    ],
  },
  comunicacions: {
    current: 'Plantilles, inbox, tracking i welcome automàtic existeixen amb dedupe i fallback.',
    zenit: 'Una veu comercial coherent: cada missatge és oportú, editable, rastrejable i premium.',
    superintendentRead: 'La captació passa per confiança; cada email o WhatsApp ha de semblar escrit per algú que domina el bolo.',
    improvements: [
      {
        label: 'Biblioteca de veu premium per moments',
        area: 'MARCA',
        current: 'Hi ha plantilles i serveis d enviament.',
        zenit: 'Cada moment té una plantilla revisada: entrada, proposta, recordatori, confirmació, post-event i referral.',
        why: 'Coherència de marca i menys improvisació.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Control d oportunitat abans d enviar',
        area: 'VENDA',
        current: 'El sistema pot enviar i trackejar.',
        zenit: 'Abans de sortir, el missatge sap estat del lead, idioma, dossier, marge i risc.',
        why: 'Evita missatges correctes en el moment equivocat.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
      {
        label: 'Inbox com a motor de captació',
        area: 'VENDA',
        current: 'L inbox pot importar i crear traça.',
        zenit: 'Entrada nova es converteix en lead qualificat, resposta recomanada i següent tasca.',
        why: 'Cap client que entra per la porta hauria de quedar sense circuit.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
    ],
  },
  'post-event': {
    current: 'Post-event ja apareix a Avui i hi ha playbook intern per tancar el cercle.',
    zenit: 'Cada bolo genera ressenya, testimoni, aprenentatge, referral i actiu comercial reutilitzable.',
    superintendentRead: 'El bolo no acaba quan es recull el material; acaba quan ha creat la propera venda.',
    improvements: [
      {
        label: 'Auto-esborrany de ressenya i testimoni',
        area: 'MARCA',
        current: 'La pantalla indica accions pendents.',
        zenit: 'El sistema prepara missatges personalitzats i fragments de testimoni revisables.',
        why: 'Prova social fresca ven més que qualsevol promesa genèrica.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Informe intern d aprenentatge',
        area: 'OPERACIO',
        current: 'Hi ha bases de report i enquestes.',
        zenit: 'Cada incidència, extra o èxit alimenta producte, pricing i checklist.',
        why: 'El sistema ha d aprendre de la realitat dels bolos.',
        impact: 'MITJA',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Referral amb timing i context',
        area: 'VENDA',
        current: 'El referral existeix com a front pendent.',
        zenit: 'Clients contents reben una petició concreta quan l experiència encara és recent.',
        why: 'És captació barata i amb confiança heretada.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
    ],
  },
  cataleg: {
    current: 'Packs, extras, inventari, productes de partner i pricing existeixen, però el valor client-facing encara pot ser més comercial.',
    zenit: 'Un catàleg que ven experiències, no llistes: valor percebut, cost intern, marge i prova visual alineats.',
    superintendentRead: 'El catàleg és on el client entén per què paga més; si només lista noms, baixa el ticket.',
    improvements: [
      {
        label: 'Fitxa comercial de producte premium',
        area: 'MARCA',
        current: 'Els productes estan modelats i es poden mostrar en diferents pantalles.',
        zenit: 'Cada producte té promesa, per a qui és, què inclou, prova visual i upsell natural.',
        why: 'Ajuda a vendre valor abans de discutir preu.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'PENDENT',
      },
      {
        label: 'Preu-cost-font per cada pack i extra',
        area: 'MARGE',
        current: 'Hi ha fonts canòniques, però cal auditoria de consistència.',
        zenit: 'Cada pack explica PVP, cost, marge, vida útil i origen del preu.',
        why: 'Sense font i marge, el catàleg pot semblar bonic però ser perillós.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
      {
        label: 'Ordenació per conversió i ticket',
        area: 'VENDA',
        current: 'El catàleg és navegable.',
        zenit: 'El sistema destaca productes que converteixen, pugen ticket o resolen objeccions.',
        why: 'La millor oferta no sempre és la més barata ni la primera alfabètica.',
        impact: 'MITJA',
        effort: 'MITJA',
        status: 'PENDENT',
      },
    ],
  },
  'visual-sistema': {
    current: 'Existeixen atles elèctric, auditoria visual, Master, Studio, protocol i guards.',
    zenit: 'Un centre de comandament per humans i IAs: què hi ha, què falla, què vendre millor i què tocar primer.',
    superintendentRead: 'El sistema ja pot mirar-se a si mateix; ara ha de convertir aquesta mirada en ordre de millora.',
    improvements: [
      {
        label: 'Passada visual humana per mòdul',
        area: 'MARCA',
        current: 'L auditoria diu si renderitza i captura bé.',
        zenit: 'Cada pantalla rep criteri humà: jerarquia, densitat, conversió, confiança i acció següent.',
        why: 'Renderitzar no és vendre ni operar bé.',
        impact: 'ALT',
        effort: 'ALT',
        status: 'PENDENT',
      },
      {
        label: 'Master com a llista de prioritats viva',
        area: 'SISTEMA',
        current: 'El Master agrupa mòduls, riscos i properes accions.',
        zenit: 'El Master ordena millores per impacte comercial, risc operatiu i esforç.',
        why: 'Evita saltar de pantalla en pantalla sense criteri.',
        impact: 'ALT',
        effort: 'MITJA',
        status: 'EN_CURS',
      },
      {
        label: 'Comparador Actual -> Zenit visible',
        area: 'SISTEMA',
        current: 'La tesi Zenit viu als docs i el Master diu què existeix.',
        zenit: 'La distància entre realitat i ambició queda visible dins `/admin/docs/master`.',
        why: 'És exactament el pont que faltava per treballar de la mà sense perdre el nord.',
        impact: 'ALT',
        effort: 'BAIX',
        status: 'EN_CURS',
      },
    ],
  },
};

export const MASTER_ATLAS_MODULES: MasterAtlasModuleDefinition[] = [
  {
    id: 'comandament',
    title: 'Comandament',
    subtitle: 'Avui, control complet, salut i lectura executiva.',
    mission: 'Fer que el propietari obri un lloc i sàpiga què toca avui, què crema marge i què pot esperar.',
    ownerQuestion: 'Què he de mirar o fer ara mateix?',
    routes: ['/admin', '/admin/control', '/admin/salut', '/admin/reporting', '/admin/economia'],
    visualGroups: ['Comandament'],
    electricPatterns: ['app/admin/page.tsx', 'app/admin/control', 'dailyBriefService', 'dashboard-data', 'operationalPulse', 'economicCockpit', 'capacityConflict', 'dayCollisionService'],
    sourceOfTruth: ['dailyBriefService', 'dashboard-data', 'capacityConflictService', 'dayCollisionService', 'leadPriorityService', 'postEventPlaybookService', 'economicCockpit'],
    docs: ['docs/TESI-MAQUINA-full-de-ruta-2026-07.md', 'docs/TESI-ZENIT-MAQUINA-ORBITA-2026-07-04.md', 'docs/admin-protocol.md'],
    operations: ['Llegir tasques i alertes', 'Triar leads del dia', 'Detectar post-event pendent', 'Veure xocs de capacitat, col·lisions de dia i caixa'],
    risks: ['Tornar a fer un dashboard immens', 'Duplicar KPIs que ja calcula dashboard-data', 'Fer que el propietari hagi d obrir massa pantalles', 'Amagar un doble bolo de dissabte fora de la pantalla Avui'],
    safeTouch: ['Afegir projeccions de serveis existents', 'Mantenir Avui calmat', 'Enviar el detall exhaustiu a /admin/control'],
    validations: ['test servei afectat', 'captura /admin desktop i mobile', 'npx tsc --noEmit', 'pnpm run validate:core'],
    nextMoves: [
      { label: 'Brief diari sortint al propietari', why: 'Transforma la brúixola en acció abans d obrir l admin.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Guàrdia de dissabtes visible a Avui', why: 'Els dies amb 2+ bolos ja apareixen a Cal que ho miris via dayCollisionService (#1421).', impact: 'ALT', effort: 'MITJA', status: 'FET' },
      { label: 'Confirmació abans de crear el segon bolo del dia', why: 'Eleva l avís existent al moment de comprometre una nova reserva.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'comercial',
    title: 'Comercial i leads',
    subtitle: 'Entrada, scoring, seguiment, resposta ràpida i conversió.',
    mission: 'Convertir demanda entrant en decisió clara: perseguir, pressupostar, descartar o convertir.',
    ownerQuestion: 'Quin lead val la pena treballar i quina és la propera acció?',
    routes: ['/admin/leads', '/admin/leads/[id]', '/admin/sales-ops', '/admin/inbox', '/admin/intake'],
    visualGroups: ['Leads', 'Comercial', 'Comunicacions'],
    electricPatterns: ['leadAdminService', 'leadRouteService', 'leadServiceLine', 'commercialScoring', 'leadPriorityService', 'automationTriggers', 'leadWelcomeEmailService', 'commercialSequenceService'],
    sourceOfTruth: ['Lead', 'LeadServiceLine', 'scoreLead', 'onLeadCreated', 'leadWelcomeEmailService', 'commercialSequenceService'],
    docs: ['docs/TESI-MAQUINA-full-de-ruta-2026-07.md', 'docs/admin-fitxes-pantalles.md'],
    operations: ['Crear lead', 'Extreure dades d email o WhatsApp', 'Prioritzar per score', 'Enviar benvinguda automàtica', 'Preparar dossier'],
    risks: ['Enviar a placeholder', 'Duplicar welcome en retry', 'Recalcular score localment', 'Confondre lead amb reserva'],
    safeTouch: ['Respectar TASK_DEDUPE_KEY.welcomeEmail', 'Usar preferredLocale i plantilla welcome', 'Deixar fallback manual si SMTP falla', 'Mantenir LeadServiceLine com pre-reserva'],
    validations: ['leadWelcomeEmailService test', 'automationTriggers test', 'lead service tests', 'smoke detail /admin/leads/[id]'],
    nextMoves: [
      { label: 'Auditar HTML/copy del welcome email', why: 'Ja s envia automàtic; ara ha de sonar premium.', impact: 'ALT', effort: 'BAIX', status: 'PENDENT' },
      { label: 'Seqüència multicanal real amb aturada en resposta', why: 'Aprofita el cervell comercial sense molestar leads que ja contesten.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
    ],
  },
  {
    id: 'documents',
    title: 'Dossiers, pressupostos i PDFs',
    subtitle: 'Proposta client-facing, snapshot, marge i document final.',
    mission: 'Presentar Òrbita com a premium sense perdre coherència econòmica ni canviar propostes antigues.',
    ownerQuestion: 'El document ven bé i protegeix el marge abans d enviar?',
    routes: ['/admin/dossiers', '/admin/presupuestos', '/admin/studio', '/api/admin/studio/preview/dossier', '/api/admin/dossiers/[id]/composite'],
    visualGroups: ['Documents', 'Sistema'],
    electricPatterns: ['dossierService', 'dossier-html-builder', 'dossierSnapshot', 'dossierProductMapping', 'dossierMarginGuard', 'dossierAutoDraft', 'proposalAdminService', 'quotePdfService'],
    sourceOfTruth: ['Dossier', 'lineSnapshot', 'dossierService', 'dossierSnapshotService', 'dossierMarginGuardService', 'dossier-html-builder'],
    docs: ['docs/TESI-ZENIT-MAQUINA-ORBITA-2026-07-04.md', 'docs/audit/FULL-DE-RUTA-auditoria-disseny-admin.md'],
    operations: ['Generar esborrany', 'Mapar línies de lead', 'Veure marge abans d enviar', 'Desar snapshot', 'Generar PDF compost'],
    risks: ['Canviar un dossier antic per catàleg nou', 'Mostrar marge intern al client', 'Fer un PDF que compila però no ven', 'Duplicar fórmules de transport'],
    safeTouch: ['Preservar lineSnapshot', 'Usar computeBoloTransport i costEngine', 'Separar UI admin de copy client-facing', 'Validar preview PDF real'],
    validations: ['dossier service tests', 'dossier-html-builder tests', 'preview PDF 200 application/pdf', 'captura dossier/PDF si canvia visual'],
    nextMoves: [
      { label: 'Auditoria client-facing del dossier complet', why: 'És el document que converteix valor en preu acceptat.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Master de plantilles PDF/email', why: 'Evita que cada document tingui una veu i una jerarquia diferent.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'reserves',
    title: 'Reserves i operativa',
    subtitle: 'Del sí al bolo executat: calendari, checklist, inventari i capacitat.',
    mission: 'Convertir un sí comercial en una operació segura, calendari ocupat i equip preparat.',
    ownerQuestion: 'Aquest bolo està preparat, cobert i no xoca amb res?',
    routes: ['/admin/bookings', '/admin/bookings/[id]', '/admin/bookings/new', '/admin/calendario', '/admin/cuadrant', '/admin/tasks'],
    visualGroups: ['Reserves', 'Operativa', 'Tasques'],
    electricPatterns: ['bookingCreationService', 'bookingRouteService', 'BookingServiceLine', 'bookingChecklistService', 'bookingInventoryService', 'capacityConflict', 'dayCollisionService', 'crewSchedule', 'onBookingConfirmed'],
    sourceOfTruth: ['Booking', 'BookingServiceLine', 'bookingCreationService', 'bookingRouteService', 'bookingChecklistService', 'capacityConflictService', 'dayCollisionService'],
    docs: ['docs/admin-fitxes-pantalles.md', 'docs/protocol-executiu.md'],
    operations: ['Crear reserva', 'Copiar service lines del lead', 'Confirmar checklist', 'Assignar inventari', 'Veure calendari/cuadrant', 'Detectar dies amb 2+ bolos compromesos'],
    risks: ['Comprometre dos bolos el mateix dia', 'Editar reserva com si encara fos lead', 'No crear checklist pre-event', 'Trencar customerId en vistes filtrades', 'Confondre xoc d inventari amb xoc de presència humana'],
    safeTouch: ['Mantenir booking com veritat post-sí', 'Usar serveis de booking', 'Validar smoke-detail en rutes [id]', 'No duplicar calendari vs cuadrant'],
    validations: ['booking service tests', 'BookingPipelineView tests', 'qa:smoke-detail', 'npx tsc --noEmit'],
    nextMoves: [
      { label: 'Guàrdia de dissabtes a Avui', why: 'Detecta dies amb 2+ reserves compromeses i els porta a Cal que ho miris (#1421).', impact: 'ALT', effort: 'MITJA', status: 'FET' },
      { label: 'Gate en crear reserva amb data ja ocupada', why: 'Converteix l avís en confirmació explícita abans de comprometre el segon bolo.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Checklist pre-event amb recordatoris T-7/T-2', why: 'Redueix memòria oral i improvisació.', impact: 'MITJA', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'economia',
    title: 'Economia, marge i cash',
    subtitle: 'Preu, cost, transport, CAC, cobrament i rendibilitat.',
    mission: 'Fer que cada decisió comercial i operativa protegeixi marge, caixa i temps escàs.',
    ownerQuestion: 'Aquest bolo guanya diners de veritat i quan entra/surt la caixa?',
    routes: ['/admin/economia', '/admin/pricing', '/admin/cost-calculator', '/admin/bookings/[id]', '/admin/collaborators/[id]'],
    visualGroups: ['Economia', 'Catàleg', 'Partners'],
    electricPatterns: ['costEngine', 'travelLaborCost', 'cashFlowForecast', 'economicCockpit', 'payment-status', 'bookingOutstandingAmount', 'collaboratorPayout', 'collaboratorAccount'],
    sourceOfTruth: ['costEngine', 'travelLaborCost', 'computeBookingFinancialSummary', 'bookingOutstandingAmount', 'collaboratorPayoutService', 'collaboratorAccountService'],
    docs: ['docs/TESI-MAQUINA-full-de-ruta-2026-07.md', 'docs/admin-protocol.md'],
    operations: ['Calcular marge', 'Calcular transport', 'Veure pendent cash-aware', 'Liquidar col·laboradors', 'Mesurar CAC'],
    risks: ['Fer toFixed+€ a la UI', 'Ignorar cashAmount', 'Duplicar costEngine', 'Barrejar preu client amb cost intern'],
    safeTouch: ['Canviar cervell econòmic, no JSX', 'Usar helpers monetaris canònics', 'Afegir test de cas econòmic', 'Validar dashboard i fitxa que consumeixen el número'],
    validations: ['costEngine tests', 'payment-status tests', 'collaboratorAccount tests', 'qa:no-admin-toFixed-currency'],
    nextMoves: [
      { label: 'Quadre de marge per dissabte ocupat', why: 'El temps escàs no és un dia: és un actiu econòmic.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Revisió de preus per marge real i CAC', why: 'Puja preus on el sistema demostri que el marge és baix.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
    ],
  },
  {
    id: 'partners',
    title: 'Partners i Masquerade',
    subtitle: 'Col·laboradors, socis-clients, productes i compte corrent.',
    mission: 'Modelar una relació externa única encara que el diner pugui anar en dues direccions.',
    ownerQuestion: 'Aquest partner em deu, li dec o estem en paus?',
    routes: ['/admin/collaborators', '/admin/collaborators/[id]', '/admin/cuadrant/repartiment'],
    visualGroups: ['Partners', 'Operativa'],
    electricPatterns: ['Collaborator', 'CLIENT_PARTNER', 'CollaboratorsClient', 'CollaboratorAccountPanel', 'collaboratorAccountService', 'collaboratorProductService', 'seed-partners'],
    sourceOfTruth: ['Collaborator', 'CollaboratorProduct', 'billedCollaboratorId', 'collaboratorAccountService', 'collaboratorPayoutService'],
    docs: ['docs/admin-diary.md', 'docs/admin-protocol.md'],
    operations: ['Filtrar CLIENT_PARTNER', 'Veure compte corrent', 'Cobrar en efectiu', 'Afegir productes de partner', 'Liquidar payout'],
    risks: ['Duplicar Carlos/Masquerade', 'Guardar client final del partner com si fos teu', 'No separar li dec vs em deu', 'Inflar marge amb cost de partner absent'],
    safeTouch: ['Una sola fitxa Collaborator', 'Facturat a partner quan ell contracta', 'Línia de partner quan el revens', 'Cost real obligatori'],
    validations: ['CollaboratorsClient test', 'collaboratorAccount tests', 'collaboratorProduct tests', 'captura fitxa partner si canvia UI'],
    nextMoves: [
      { label: 'Vista de liquidació mensual partner', why: 'Converteix el compte corrent en acció de tancament de mes.', impact: 'MITJA', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Auditoria de productes partner amb markup', why: 'Evita marge fals i preu inconsistent en dossiers.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'comunicacions',
    title: 'Comunicacions i plantilles',
    subtitle: 'Inbox, emails, plantilles BD, tracking i processos client-facing.',
    mission: 'Fer que la màquina parli amb el to correcte, sense duplicar enviaments ni perdre traça.',
    ownerQuestion: 'Què ha sortit cap al client i què falta revisar o enviar?',
    routes: ['/admin/inbox', '/admin/emails', '/admin/email-templates', '/admin/settings/notifications'],
    visualGroups: ['Comunicacions', 'Sistema'],
    electricPatterns: ['emailTemplateService', 'adminEmailSendService', 'emailTrackingService', 'inboxLeadImportService', 'leadWelcomeEmailService', 'bookingConfirmationEmailService', 'customerProcessService'],
    sourceOfTruth: ['EmailTemplate', 'emailTemplateService', 'sendEmail', 'adminEmailSendService', 'emailTrackingService', 'TASK_DEDUPE_KEY'],
    docs: ['docs/audit/FULL-DE-RUTA-auditoria-disseny-admin.md', 'docs/admin-protocol.md'],
    operations: ['Editar plantilla', 'Enviar email', 'Importar inbox', 'Track open/click', 'Crear fallback manual'],
    risks: ['Hardcodejar copy client-facing', 'Enviar sense idempotència', 'No respectar locale', 'Confondre pendent d enviar amb pendent de resposta'],
    safeTouch: ['Plantilles BD per copy', 'DedupeKey per automatismes', 'Fallback manual si falla', 'No mailto a admin'],
    validations: ['email service tests', 'automation tests', 'qa:admin-no-mailto', 'captura/render HTML email si canvia plantilla'],
    nextMoves: [
      { label: 'Auditoria visual d emails', why: 'El client jutja marca i professionalitat pels emails.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Taula de processos outward-facing amb fre humà', why: 'Permet automatitzar més sense perdre control.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'post-event',
    title: 'Post-event i volant',
    subtitle: 'Ressenyes, testimonis, referrals, informes i aprenentatge.',
    mission: 'Convertir cada bolo fet en prova social, aprenentatge i el següent lead més barat.',
    ownerQuestion: 'Què falta demanar després del bolo perquè no es perdi valor?',
    routes: ['/admin/post-event', '/admin/post-event/playbook', '/admin/post-event/reports', '/admin/post-event/surveys', '/admin/ressenyes'],
    visualGroups: ['Post-event', 'Web'],
    electricPatterns: ['postEventPlaybookService', 'postEventDispatchService', 'questionnaireService', 'reviewsSyncService', 'referralsService', 'reactivationService'],
    sourceOfTruth: ['postEventPlaybookService', 'PostEventReport', 'ClientSurvey', 'reviewsSyncService', 'referralsService'],
    docs: ['docs/TESI-MAQUINA-full-de-ruta-2026-07.md', 'docs/audit/FULL-DE-RUTA-auditoria-disseny-admin.md'],
    operations: ['Veure accions pendents', 'Enviar enquesta', 'Demanar ressenya', 'Crear testimoni', 'Generar referral'],
    risks: ['Enviar massa aviat o sense context', 'Barrejar informe intern amb missatge al client', 'No tancar el loop a la home'],
    safeTouch: ['Primer lectura interna', 'Després esborrany', 'Finalment auto-dispatch amb autorització', 'Separar report intern de copy client'],
    validations: ['post-event tests', 'captura /admin/post-event', 'test dispatch si toca enviament', 'validate:core'],
    nextMoves: [
      { label: 'Auto-esborrany post-event amb revisió', why: 'Accelera CAC barat sense enviar sol de cop.', impact: 'ALT', effort: 'MITJA', status: 'PENDENT' },
      { label: 'Portfolio/testimoni des de bolo completat', why: 'Converteix execució real en actiu comercial.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
    ],
  },
  {
    id: 'cataleg',
    title: 'Catàleg, packs i inventari',
    subtitle: 'Producte, cost, equip, extras, pricing i fonts de valor.',
    mission: 'Fer que el que es ven tingui cost, preu, vida útil i presentació coherents.',
    ownerQuestion: 'Aquest producte està ben valorat, costa el que diu i es pot vendre així?',
    routes: ['/admin/packs', '/admin/packs/extras', '/admin/pricing', '/admin/inventory', '/admin/catalog'],
    visualGroups: ['Catàleg', 'Inventari'],
    electricPatterns: ['packs', 'PACKS', 'inventory', 'pricing', 'collaboratorProduct', 'animacio-products', 'packPricing', 'cost-calculator'],
    sourceOfTruth: ['lib/constants/animacio-products.ts', 'Pack', 'InventoryItem', 'collaboratorProductService', 'pricing model'],
    docs: ['docs/audit/FULL-DE-RUTA-auditoria-disseny-admin.md', 'docs/admin-protocol.md'],
    operations: ['Editar pack', 'Afegir extra', 'Valorar inventari', 'Sincronitzar preu', 'Calcular cost'],
    risks: ['Preu sense font', 'Cost d inventari absent', 'Pack amb PVP diferent segons pantalla', 'Catàleg client desalineat del pressupost'],
    safeTouch: ['Font única de preus', 'Tests de pack/pricing', 'No duplicar catàlegs locals', 'Verificar preview client si canvia presentació'],
    validations: ['pack pricing tests', 'inventory tests', 'i18n packs/equipment guards', 'qa:layer-catalogs'],
    nextMoves: [
      { label: 'Auditoria preu-cost de packs i extras', why: 'És marge directe i posicionament de marca.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
      { label: 'Fitxa visual de producte client-facing', why: 'El catàleg ha de vendre el valor, no només listar noms.', impact: 'MITJA', effort: 'MITJA', status: 'PENDENT' },
    ],
  },
  {
    id: 'visual-sistema',
    title: 'Visual, sistema i continuïtat',
    subtitle: 'Atles, auditoria visual, protocol, crons, settings i eines internes.',
    mission: 'Fer que el repo sigui operable per humans i IAs sense memòria oral.',
    ownerQuestion: 'On miro abans de tocar i com sé que no estic trencant res?',
    routes: ['/admin/docs/master', '/admin/docs/electric-atlas', '/admin/docs/visual-audit', '/admin/studio', '/admin/settings', '/admin/crons', '/admin/scripts'],
    visualGroups: ['Sistema'],
    electricPatterns: ['repoElectricAtlasService', 'visualAuditAtlasService', 'admin-visual-audit', 'adminNav', 'AdminPage', 'admin-protocol', 'agent-sync'],
    sourceOfTruth: ['CLAUDE.md', 'docs/admin-protocol.md', 'docs/agent-sync.md', 'repoElectricAtlasService', 'visualAuditAtlasService', 'adminNav'],
    docs: ['CLAUDE.md', 'docs/protocol-executiu.md', 'docs/admin-protocol.md', 'docs/audit/AUDITORIA-VISUAL-GLOBAL-1416.md'],
    operations: ['Consultar manual', 'Buscar cable', 'Mirar captures', 'Validar protocol', 'Executar guards'],
    risks: ['Fer documentació morta', 'Confondre render OK amb disseny perfecte', 'No actualitzar counter', 'Treballar sense mirar agent-sync'],
    safeTouch: ['Docs vius dins admin', 'Serveis que llegeixen repo real', 'Guards de protocol', 'Captures abans/després per visual'],
    validations: ['repoElectricAtlasService test', 'visualAuditAtlasService test', 'qa:protocol', 'validate:core', 'audit:visual:admin si canvia visual'],
    nextMoves: [
      { label: 'Auditoria visual humana per mòdul', why: 'El baseline diu que renderitza; falta criteri de disseny.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
      { label: 'Fitxes forenses pendents per òrgan', why: 'Permet tocar pantalles sense obrir illes mortes.', impact: 'ALT', effort: 'ALT', status: 'PENDENT' },
    ],
  },
] as const;
