export const PUBLIC_BOOKING_ERROR_CODES = [
  'MISSING_REQUIRED_FIELDS',
  'INVALID_EMAIL',
  'INVALID_EVENT_TYPE',
  'INVALID_EVENT_DATE',
  'EVENT_DATE_PAST',
  'INVALID_GUEST_COUNT',
  'INVALID_EXTRA_HOURS',
  'INVALID_PACK',
  'INVALID_EXTRAS',
  'DATE_UNAVAILABLE',
  'BOOKING_CREATE_FAILED',
] as const;
