export const REPO_ATLAS_EXCLUDED_DIRS = [
  '.git',
  '.next',
  'node_modules',
  'coverage',
  'playwright-report',
  'test-results',
  'uploads',
  '.codex-captures',
] as const;

export const REPO_ATLAS_SENSITIVE_FILE_PATTERNS = [
  '.env',
  '.env.local',
  '.env.development',
  '.env.production',
  '.npmrc',
  '.sentryclirc',
  '*.log',
] as const;

export const REPO_ATLAS_TEXT_EXTENSIONS = [
  '.bat',
  '.css',
  '.html',
  '.js',
  '.json',
  '.md',
  '.mjs',
  '.mts',
  '.prisma',
  '.sh',
  '.sql',
  '.svg',
  '.toml',
  '.ts',
  '.tsx',
  '.txt',
  '.webmanifest',
  '.yaml',
  '.yml',
] as const;

export const REPO_ATLAS_FLOW_DEFINITIONS = [
  {
    id: 'lead-to-booking',
    title: 'Lead entrant -> reserva',
    question: 'Com entra una oportunitat, com es qualifica i com acaba en reserva?',
    stages: [
      { label: 'Entrada publica', intent: 'Formularis, configurador i APIs publiques que creen demanda.', patterns: ['app/[locale]', 'app/api/contact', 'app/api/booking', 'app/api/public'] },
      { label: 'Lead admin', intent: 'CRM, score, estat, notes, activitats, service lines pre-reserva i welcome automatic.', patterns: ['app/admin/leads', 'app/api/admin/leads', 'leadRouteService', 'leadAdminService', 'leadServiceLine', 'automationTriggers', 'leadWelcomeEmailService'] },
      { label: 'Documents comercials', intent: 'Pressupost/dossier abans de tancar.', patterns: ['app/admin/dossiers', 'app/admin/presupuestos', 'dossier', 'proposal'] },
      { label: 'Reserva', intent: 'Creacio i manteniment de la reserva com a veritat post-tancament.', patterns: ['app/admin/bookings', 'app/api/admin/bookings', 'bookingCreationService', 'bookingRouteService', 'BookingServiceLine'] },
      { label: 'Calendari i operativa', intent: 'El dia ocupa capacitat real i entra al calendari/cuadrant.', patterns: ['calendario', 'calendar', 'cuadrant', 'capacity', 'crewSchedule'] },
    ],
  },
  {
    id: 'money-margin',
    title: 'Preu, cost, marge i cash',
    question: 'D on surten els euros i quina funcio mana cada numero?',
    stages: [
      { label: 'Preu ofert', intent: 'Productes, packs, linies i transport que formen ingressos.', patterns: ['packs', 'pricing', 'LeadServiceLine', 'BookingServiceLine', 'dossierMargin'] },
      { label: 'Cost real', intent: 'Cost de producte, inventari, proveidor, ruta i personal.', patterns: ['costEngine', 'travelLaborCost', 'inventory', 'collaboratorProduct', 'fuelReference'] },
      { label: 'Marge', intent: 'Resum economic canonic; no recalcular a la UI.', patterns: ['computeBookingFinancialSummary', 'margin', 'economic', 'profitability'] },
      { label: 'Pagaments', intent: 'Bestreta, resta, Bizum, Stripe i efectiu.', patterns: ['payment', 'Stripe', 'Bizum', 'cashAmount', 'payment-status'] },
      { label: 'Payout', intent: 'Que cobra cada col.laborador i saldo amb partners.', patterns: ['repartiment', 'collaboratorPayout', 'collaboratorAccount', 'CollaboratorPayment'] },
    ],
  },
  {
    id: 'dossier-pdf',
    title: 'Dossier / pressupost / PDF',
    question: 'Com es genera una proposta revisable i estable?',
    stages: [
      { label: 'Seleccio', intent: 'El propietari tria o auto-esborra productes del lead.', patterns: ['DossierGeneratorClient', 'dossierDraftSuggestion', 'dossierAutoDraft', 'dossierProductMapping'] },
      { label: 'Snapshot', intent: 'Foto immutable del que s ha proposat.', patterns: ['dossierSnapshot', 'lineSnapshot', 'productIds'] },
      { label: 'Marge abans d enviar', intent: 'Guard intern abans de presentar al client.', patterns: ['dossierMarginGuard', 'computeBookingFinancialSummary', 'computeBoloTransport'] },
      { label: 'HTML editorial', intent: 'Narrativa del dossier client-facing.', patterns: ['dossier-html-builder', 'dossier-copy'] },
      { label: 'PDF complet', intent: 'Composicio final dossier + cataleg filtrat.', patterns: ['dossierCompositePdf', 'catalogPdfService', 'composite/route'] },
    ],
  },
  {
    id: 'partner-masquerade',
    title: 'Partners i Masquerade',
    question: 'Com es modela un soci que pot contractar-nos i ser proveidor?',
    stages: [
      { label: 'Fitxa unica', intent: 'Carlos Lucas i Masquerade viuen com un Collaborator amb rols.', patterns: ['Collaborator', 'CLIENT_PARTNER', 'CollaboratorsClient', 'seed-partners'] },
      { label: 'Ens contracta', intent: 'Reserva facturada al partner, sense client final del partner.', patterns: ['billedCollaboratorId', 'BookingBilledCollaborator', 'collaboratorAccount'] },
      { label: 'El contractem', intent: 'Linies o productes del partner amb cost intern i markup.', patterns: ['CollaboratorProduct', 'sourceCollaboratorId', 'collaboratorProductService'] },
      { label: 'Compte corrent', intent: 'Li dec vs em deu i saldo net.', patterns: ['collaboratorAccountService', 'CollaboratorAccountPanel', 'collaboratorPayout'] },
    ],
  },
  {
    id: 'post-event-wheel',
    title: 'Post-event i volant comercial',
    question: 'Com es tanca el cercle despres del bolo?',
    stages: [
      { label: 'Bolo completat', intent: 'La reserva ja ha passat i pot generar seguiment.', patterns: ['COMPLETED', 'bookingRouteService', 'post-event'] },
      { label: 'Playbook', intent: 'Accions de gracies, ressenya, testimoni i referral.', patterns: ['postEventPlaybook', 'testimonial', 'review', 'referral'] },
      { label: 'Comunicacio', intent: 'Emails, inbox i tracking si el propietari activa enviament.', patterns: ['email', 'inbox', 'tracking', 'send-post-event'] },
      { label: 'Aprenentatge', intent: 'Reports, surveys i respostes reals del client.', patterns: ['postEventReport', 'ClientSurvey', 'CustomerTestimonial', 'reports'] },
    ],
  },
] as const;

export const REPO_ATLAS_TOUCHPOINT_DEFINITIONS = [
  {
    id: 'change-margin',
    title: 'Canviar marge, preu o cost',
    when: 'Quan una xifra economica no quadra, o vols canviar com es calcula marge/transport/payout.',
    readFirst: ['CLAUDE.md', 'docs/admin-protocol.md', 'lib/services/costEngine.ts', 'lib/services/travelLaborCost.ts'],
    touchPatterns: ['costEngine', 'travelLaborCost', 'margin', 'pricing', 'collaboratorPayout', 'repartiment', 'payment-status'],
    safeOrder: ['Troba la funcio canonica', 'Amplia el cervell, no la UI', 'Actualitza tests del servei', 'Verifica pantalla que consumeix el numero', 'Passa validate:core i build'],
    doNotTouch: ['No calcular marge en JSX', 'No crear constants locals de diners', 'No duplicar transport fora de travelLaborCost'],
    validations: ['test del servei economic afectat', 'npx tsc --noEmit', 'pnpm run validate:core', 'pnpm build'],
  },
  {
    id: 'change-dossier',
    title: 'Canviar dossier, pressupost o PDF',
    when: 'Quan vols canviar proposta, snapshot, annexos, PDF complet o marge abans d enviar.',
    readFirst: ['app/admin/dossiers/page.tsx', 'app/admin/dossiers/DossierGeneratorClient.tsx', 'lib/services/dossierService.ts', 'lib/utils/dossier-html-builder.ts'],
    touchPatterns: ['dossier', 'proposal', 'catalogPdf', 'pdf', 'lineSnapshot', 'dossier-html-builder'],
    safeOrder: ['Distingir UI admin vs document client-facing', 'Preservar lineSnapshot', 'No enviar email real en proves', 'Validar PDF/preview', 'Captura desktop i mobile si canvia UI'],
    doNotTouch: ['No fer que un dossier antic canviï per cataleg nou', 'No posar marge intern al PDF client', 'No enviar outward-facing sense toggle'],
    validations: ['tests dossier/PDF', 'preview PDF 200 application/pdf', 'npx tsc --noEmit', 'pnpm run validate:core', 'pnpm build'],
  },
  {
    id: 'change-lead-autopilot',
    title: 'Canviar autopilot de lead / email de benvinguda',
    when: 'Quan vols tocar la resposta automatica que surt cap al lead nou.',
    readFirst: ['lib/services/automationTriggers.ts', 'lib/services/leadWelcomeEmailService.ts', 'lib/services/emailTemplateService.ts', 'app/admin/email-templates'],
    touchPatterns: ['onLeadCreated', 'leadWelcomeEmail', 'TASK_DEDUPE_KEY.welcomeEmail', 'welcome', 'isSmtpConfigured'],
    safeOrder: ['Confirmar decisio outward-facing del propietari', 'Mantenir dedupeKey com a lock idempotent i audit', 'No enviar mai a placeholders', 'Usar plantilla editable i preferredLocale', 'Deixar tasca manual si SMTP off o falla'],
    doNotTouch: ['No saltar el dedupeKey', 'No enviar dos emails en retry o double-click', 'No hardcodejar copy client-facing fora de la plantilla welcome'],
    validations: ['leadWelcomeEmailService test', 'automationTriggers test', 'npx tsc --noEmit', 'pnpm run validate:core'],
  },
  {
    id: 'change-partner',
    title: 'Canviar partners / Masquerade / col.laboradors',
    when: 'Quan un partner es proveidor, client, referidor o les dues direccions alhora.',
    readFirst: ['prisma/schema.prisma', 'app/admin/collaborators/CollaboratorsClient.tsx', 'lib/services/collaboratorAccountService.ts'],
    touchPatterns: ['Collaborator', 'CollaboratorProduct', 'CLIENT_PARTNER', 'billedCollaboratorId', 'collaboratorAccount', 'collaboratorPayout'],
    safeOrder: ['Mantenir una sola fitxa', 'Separar direccio del diner', 'Facturat a partner si ell contracta', 'Producte partner si el revens', 'Validar saldo net'],
    doNotTouch: ['No duplicar Carlos/Masquerade com a client i col.laborador separat', 'No posar el client final del partner com a client teu'],
    validations: ['tests collaborator*', 'captura fitxa partner', 'npx tsc --noEmit', 'pnpm run validate:core'],
  },
  {
    id: 'change-cash',
    title: 'Canviar efectiu / pagament el dia del bolo',
    when: 'Quan el cobrament normal es fa en efectiu i cal evitar deutes falsos.',
    readFirst: ['lib/payment-status.ts', 'app/admin/bookings/[id]/CashPaymentButton.tsx', 'app/admin/lib/dashboard-data.ts'],
    touchPatterns: ['cashAmount', 'CashPaymentButton', 'bookingOutstandingAmount', 'depositPaid', 'remainingPaid', 'payment'],
    safeOrder: ['Fer servir bookingOutstandingAmount', 'Restar cash abans de dir pendent', 'Tancar via CashPaymentButton si es UI', 'Validar dashboard i compte corrent'],
    doNotTouch: ['No assumir flags online com a unica veritat', 'No comptar cash com a deute'],
    validations: ['test cash total i cash parcial', 'npx tsc --noEmit', 'pnpm run validate:core'],
  },
  {
    id: 'change-post-event',
    title: 'Canviar post-event / ressenyes / referrals',
    when: 'Quan vols activar el volant comercial despres del bolo.',
    readFirst: ['lib/services/postEventPlaybookService.ts', 'app/admin/post-event', 'app/admin/page.tsx'],
    touchPatterns: ['postEvent', 'review', 'testimonial', 'referral', 'survey', 'feedback'],
    safeOrder: ['Distingir lectura interna vs enviament real', 'Primer fer visible la feina', 'Despres esborrany', 'Finalment auto-dispatch amb toggle'],
    doNotTouch: ['No enviar correus sols sense decisio del propietari', 'No barrejar reports interns amb copy client-facing'],
    validations: ['tests post-event', 'captura admin', 'npx tsc --noEmit', 'pnpm run validate:core'],
  },
] as const;

export const REPO_ATLAS_DOMAIN_DICTIONARY = [
  {
    id: 'lead',
    term: 'Lead',
    definition: 'Oportunitat abans de reserva. Pot tenir service lines, score, activitats, documents i estat comercial.',
    useWhen: 'Qualificar, pressupostar, preparar dossier o decidir si val la pena perseguir.',
    sourceOfTruth: ['Lead', 'LeadServiceLine', 'leadRouteService', 'leadAdminService', 'scoreLead'],
    validations: ['lead service tests', 'lead UI smoke/detail si toca pantalla'],
  },
  {
    id: 'booking',
    term: 'Booking / Reserva',
    definition: 'Veritat post-tancament del bolo: data, client/facturat a, pagaments, inventari, calendari i operativa.',
    useWhen: 'Quan el client ja ha dit si i el dia ocupa capacitat real.',
    sourceOfTruth: ['Booking', 'BookingServiceLine', 'bookingCreationService', 'bookingRouteService', 'bookingListService'],
    validations: ['booking service tests', 'smoke-detail si toca [id]'],
  },
  {
    id: 'service-line',
    term: 'ServiceLine',
    definition: 'Unitat de producte/preu/cost. En lead es configura; en booking es converteix en veritat operativa.',
    useWhen: 'Afegir productes, hores, partners, transport o configurar oferta.',
    sourceOfTruth: ['LeadServiceLine', 'BookingServiceLine', 'dossierProductMappingService'],
    validations: ['service-line tests', 'costEngine tests si impacta diners'],
  },
  {
    id: 'cost-engine',
    term: 'CostEngine',
    definition: 'Cervell economic del bolo. Qualsevol marge o cost important ha de sortir d aqui o dels cervells economics adjacents.',
    useWhen: 'Marge, cost, ingressos, transport, partner markup o rendibilitat.',
    sourceOfTruth: ['costEngine', 'computeBookingFinancialSummary', 'travelLaborCost', 'dossierMarginGuard'],
    validations: ['costEngine tests', 'dossier margin tests si pre-venda'],
  },
  {
    id: 'dossier',
    term: 'Dossier',
    definition: 'Document comercial revisable i enviable. Ha de poder congelar la proposta amb lineSnapshot.',
    useWhen: 'Presentar proposta, generar PDF complet o enviar pressupost editorial.',
    sourceOfTruth: ['Dossier', 'DossierGeneratorClient', 'dossierService', 'dossierSnapshotService', 'dossierCompositePdfService'],
    validations: ['dossier/PDF tests', 'preview PDF real'],
  },
  {
    id: 'line-snapshot',
    term: 'lineSnapshot',
    definition: 'Foto immutable del que es va proposar. Evita que un dossier antic canvii quan canvia el cataleg.',
    useWhen: 'Desar, reenviar o generar PDF de dossiers.',
    sourceOfTruth: ['lineSnapshot', 'dossierSnapshotService'],
    validations: ['snapshot tests', 'PDF complet 200'],
  },
  {
    id: 'collaborator',
    term: 'Collaborator / Partner',
    definition: 'Persona o empresa externa que pot ser proveidor, referidor o client-partner.',
    useWhen: 'Masquerade, Tino, col.laboradors, productes externs, payout o compte corrent.',
    sourceOfTruth: ['Collaborator', 'CollaboratorProduct', 'CLIENT_PARTNER', 'collaboratorAccountService', 'collaboratorPayoutService'],
    validations: ['collaborator service tests', 'fitxa partner'],
  },
  {
    id: 'billed-collaborator',
    term: 'billedCollaboratorId',
    definition: 'Camp que diu que una reserva es factura a un partner. Serveix quan Masquerade contracta Orbita.',
    useWhen: 'Bolos on el teu client real es el partner, no el client final del partner.',
    sourceOfTruth: ['billedCollaboratorId', 'BookingBilledCollaborator', 'collaboratorAccountService'],
    validations: ['account tests', 'calendari continua ocupat'],
  },
  {
    id: 'cash-amount',
    term: 'cashAmount',
    definition: 'Efectiu cobrat. Ha de reduir o tancar pendent encara que els flags online siguin false.',
    useWhen: 'Cobrament el mateix dia, compte corrent, dashboard pendent de cobrar.',
    sourceOfTruth: ['cashAmount', 'bookingOutstandingAmount', 'CashPaymentButton', 'getPaymentBand'],
    validations: ['cash tests total/parcial', 'dashboard pending'],
  },
  {
    id: 'post-event',
    term: 'Post-event',
    definition: 'Volant de ressenya, testimoni, feedback i referral despres del bolo.',
    useWhen: 'Tancar el cercle comercial i aprofitar clients contents.',
    sourceOfTruth: ['postEventPlaybookService', 'postEventPendingService', 'postEventDispatchService', 'Booking.postEventEmailSent', 'PostEventReport', 'ClientSurvey', 'CustomerTestimonial'],
    validations: ['post-event tests', 'captura seccio Tanca el cercle'],
  },
  {
    id: 'admin-protocol',
    term: 'Protocol',
    definition: 'Contracte de treball del repo: counter, diari, sync, validacions, monocapa i no tocar a cegues.',
    useWhen: 'Abans de qualsevol canvi real.',
    sourceOfTruth: ['CLAUDE.md', 'docs/agent-sync.md', 'docs/admin-protocol.md', 'docs/admin-diary.md'],
    validations: ['pnpm run qa:protocol', 'pnpm run validate:core'],
  },
] as const;

export const REPO_ATLAS_SYNTHESIS = {
  verdict: 'Orbita no es una web amb admin: es una maquina CRM/ERP comercial i operativa. La web capta; l admin governa; Prisma conserva la veritat; els serveis calculen; les pantalles nomes mostren i accionen.',
  goldenRules: [
    'Un calcul = un cervell. Si una xifra es recalcula en JSX, es un bug.',
    'Lead configura abans de reservar; Booking mana despres de reservar.',
    'Dossier ven cap enfora; marge i risc queden cap endins.',
    'Partner no vol dir nomes proveidor: pot ser client-partner, referidor i proveidor en una sola fitxa.',
    'CashAmount compta com a diner cobrat; no crear deutes falsos per flags online.',
    'Post-event es CAC barat: si no es veu a Avui, es perd oportunitat.',
    'Cap IA toca sense mirar protocol, atles i servei canonic.',
  ],
  useThisAtlasFor: [
    'Buscar el cable exacte abans de tocar.',
    'Trobar la font de veritat d un concepte.',
    'Veure quins fitxers entren en un flux de negoci.',
    'Decidir proves i guards abans de modificar.',
    'Evitar duplicar pantalles, serveis o formules.',
  ],
} as const;
